source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ReactiveCache_Example', :exclusive => true do
  pod "ReactiveCache", :path => "../"
end

target 'ReactiveCache_Tests', :exclusive => true do
  pod "ReactiveCache", :path => "../"

  
end
